[package]
name = "silver"
version = "0.1.0"
authors = ["reujab <reujab@gmail.com>"]

[dependencies]
clap = {version = "2.32.0", features = ["yaml"]}
lazy_static = "1.0.1"
regex = "1.0.1"
rust-ini = "0.12.2"
